### ISSUE TITLE
Cannot read values from lm-sensors library since they are not accessible from container

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/provider_system#8]
## Expected Behavior
 - We should be able to access CPU temperature from host

## Current Behavior
 - Temperature is not accessible

## Possible Solution
 - Run container in privilege mode 

## Comments
N/A

## Environment Used
- Project version : 1.0 
- docker version : 19.03.8, build afacb8
- docker-compose version : 1.25.5, build 8a1c60f

**Comment by Kam0ss** [comment]
@supertoto29 I think this is not an issue anymore, right ?

**Comment by supertoto29** [comment]
No we can read the temperature
